name: tpBow
version: '1.0'
main: org.Bow.tpBow.TpBow
api-version: '1.20'
authors: [ erhzad ]
description: a magic bow that teleported you

commands:
  givebow:
    description: give a magic bow
    usage: /givebow | /givebow <player>

permissions:
  bow.get:
    description: allow /givebow
  bow.other:
    description: allow /givebow <player>

